global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["${PC1_TARGET}"]
        labels:
          alias: "${PC1_ALIAS}"
          ip: "${PC1_IP}"
    relabel_configs:
      - target_label: instance
        replacement: "node_exporter:9100"

  - job_name: "dcgm"
    static_configs:
      - targets: ["dcgm-exporter:9400"]
